"""
Regression test for the full CLI pipeline.

Strategy
--------
The golden fixture CSVs in tests/fixtures/golden/ were generated by running:

    mddtoolkit -i example/sample_synthetic_data.csv \
               -c example/config.yaml \
               -o <output_dir>

With seed=0 fixed in config.yaml the computation is fully deterministic, so
re-running the same pipeline on the same inputs must produce bit-identical
combined_results_*.csv files.

If you intentionally change something that affects numerical output, regenerate
the fixtures by running:

    mddtoolkit -i example/sample_synthetic_data.csv \
               -c example/config.yaml \
               -o tests/fixtures/golden_run

    cp tests/fixtures/golden_run/chisq/combined_results_chisq.csv \
       tests/fixtures/golden/
    cp tests/fixtures/golden_run/percent_frac/combined_results_percent_frac.csv \
       tests/fixtures/golden/
"""
import pandas as pd
import pytest
from pathlib import Path

from diffusion_kinetics.pipeline.multi_pipeline import MultiPipeline

REPO_ROOT = Path(__file__).parent.parent
EXAMPLE_DIR = REPO_ROOT / "example"
FIXTURES_DIR = Path(__file__).parent / "fixtures" / "golden"

CONFIG_PATH = EXAMPLE_DIR / "config.yaml"
DATA_PATH = EXAMPLE_DIR / "sample_synthetic_data.csv"

MISFIT_STATS = ["chisq", "percent_frac"]


@pytest.fixture(scope="module")
def pipeline_output(tmp_path_factory):
    """Run the full pipeline once and return the output directory."""
    out_dir = tmp_path_factory.mktemp("pipeline_out")
    MultiPipeline(str(out_dir)).run(str(CONFIG_PATH), str(DATA_PATH))
    return out_dir


@pytest.mark.parametrize("stat", MISFIT_STATS)
def test_combined_results_match_golden(pipeline_output, stat):
    """combined_results_{stat}.csv must exactly match the golden fixture."""
    result_path = pipeline_output / stat / f"combined_results_{stat}.csv"
    golden_path = FIXTURES_DIR / f"combined_results_{stat}.csv"

    assert result_path.exists(), f"Pipeline did not produce {result_path.name}"
    assert golden_path.exists(), (
        f"Golden fixture missing: {golden_path}\n"
        "Run the pipeline once and copy the output — see module docstring."
    )

    result = pd.read_csv(result_path, index_col=0)
    golden = pd.read_csv(golden_path, index_col=0)

    pd.testing.assert_frame_equal(
        result,
        golden,
        check_exact=True,
        obj=f"combined_results_{stat}.csv",
    )
